services:
  ajv-validator:
    image: eq-questionnaire-validator-ajv:${TAG}-ajv
    networks:
      - eq-schema
    ports:
      - 5002:5002

  py-validator:
    image: eq-questionnaire-validator:${TAG}
    networks:
      - eq-schema
    environment:
      AJV_VALIDATOR_HOST: ajv-validator
    ports:
      - 5001:5000
    depends_on:
      - ajv-validator
networks:
  eq-schema:
    driver: bridge
